
(()=>{'use strict';
const $=s=>document.querySelector(s),canvas=$('#aquarium'),ctx=canvas.getContext('2d',{alpha:false,desynchronized:true});
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,rand=(a,b)=>Math.random()*(b-a)+a,choice=a=>a[Math.floor(Math.random()*a.length)];
let W=innerWidth,H=innerHeight,DPR=1,last=performance.now(),elapsed=0,night=false,scare=null,frameCount=0,fpsClock=performance.now(),toastTimer=0,manifest=window.AQUARIUM_MANIFEST||null,assets={},sandPattern=null,audio={ambient:null,feed:null,bubble:null},audioUnlocked=false,paused=false,booted=false;
const defaults={separation:1.65,alignment:1.05,cohesion:.88,speed:1,bubbleRate:1,volume:.55,sound:false,caustics:true};
let cfg={...defaults,...readStore('living-aquarium-settings')};
const fish=[],food=[],bubbles=[],plants=[],decor=[],critters=[],motes=[];
const species=[
 {name:'рыба-клоун',sprite:'fish/clownfish',size:[78,102],speed:[58,82],turn:58},
 {name:'скалярия',sprite:'fish/angelfish',size:[70,92],speed:[45,66],turn:48},
 {name:'тропическая',sprite:'fish/tropical-fish',size:[80,106],speed:[60,86],turn:62},
 {name:'рыба-бабочка',sprite:'fish/butterflyfish',size:[77,100],speed:[52,76],turn:55},
 {name:'золотая рыбка',sprite:'fish/goldfish',size:[80,108],speed:[47,70],turn:50},
 {name:'голубой хирург',sprite:'fish/blue-tang',size:[82,108],speed:[58,84],turn:59}
];
const decorNames=['decor/coral-pink-branch','decor/coral-yellow-sponge','decor/coral-purple-fan','decor/coral-orange-garden','decor/coral-pink-bush','decor/coral-mixed-reef','decor/shell-pearl','decor/starfish','decor/conch-shell','decor/rock-blue','decor/rock-slab','decor/rock-mossy','decor/rock-coral'];
const plantNames=['laminaria-tall-wave','laminaria-ribbon-pair','laminaria-cluster','seagrass-fine','seagrass-sway','bush-round','bush-spiky','coral-branch','coral-fan','coral-candelabra'];
const critterNames=['creatures/golden-snail','creatures/pink-shrimp','creatures/orange-shrimp','creatures/pearl-shrimp','creatures/mint-snail'];
function readStore(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch{return {}}}function writeStore(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
function hash(n){const x=Math.sin(n*127.1)*43758.5453123;return x-Math.floor(x)}function noise1(x){const i=Math.floor(x),f=x-i,u=f*f*(3-2*f);return lerp(hash(i),hash(i+1),u)*2-1}
function seeded(seed){let s=seed>>>0;return()=>((s=Math.imul(1664525,s)+1013904223>>>0)/4294967296)}
function setLoadProgress(done,total,message='Загружаем подводный мир…'){const ratio=total?done/total:0,$bar=$('#loaderBar'),$msg=$('#loaderMessage');if($bar)$bar.style.width=Math.round(ratio*100)+'%';if($msg)$msg.textContent=message+' '+Math.round(ratio*100)+'%'}
async function loadImage(src,timeout=15000){return new Promise((resolve,reject)=>{const im=new Image(),timer=setTimeout(()=>reject(new Error('Превышено время загрузки: '+src)),timeout);im.onload=()=>{clearTimeout(timer);resolve(im)};im.onerror=()=>{clearTimeout(timer);reject(new Error('Не удалось загрузить '+src))};im.src=src})}
async function loadAssets(){if(!manifest)throw new Error('Манифест ассетов не найден. Проверьте assets/manifest.js');assets={};const imageEntries=[...Object.entries(manifest.atlases).map(([name,data])=>[name,data.file]),...Object.entries(manifest.images)];let done=0,total=imageEntries.length;setLoadProgress(0,total,'Подготавливаем ассеты…');for(const [name,src] of imageEntries){assets[name]=await loadImage(src);done++;setLoadProgress(done,total,'Загружаем графику…')}audio.ambient=new Audio(manifest.audio.ambient);audio.ambient.loop=true;audio.ambient.preload='auto';audio.feed=new Audio(manifest.audio.feed);audio.feed.preload='auto';audio.bubble=new Audio(manifest.audio.bubble);audio.bubble.preload='auto';applyVolume();setLoadProgress(total,total,'Готово')}
function spriteInfo(name){return manifest.sprites[name]}
function drawSprite(name,x,y,w,{flip=false,rotation=0,alpha=1,shadow=0,anchorY=.5}={}){const s=spriteInfo(name);if(!s)return;const im=assets[s.atlas],h=w*s.h/s.w;ctx.save();ctx.translate(x,y);ctx.rotate(rotation);if(flip)ctx.scale(-1,1);ctx.globalAlpha=alpha;if(shadow){ctx.shadowColor='rgba(0,0,0,.32)';ctx.shadowBlur=0;ctx.shadowOffsetY=2}ctx.drawImage(im,s.x,s.y,s.w,s.h,-w/2,-h*anchorY,w,h);ctx.restore();}
function coverImage(im,x,y,w,h,alpha=1){const r=Math.max(w/im.width,h/im.height),iw=im.width*r,ih=im.height*r;ctx.save();ctx.globalAlpha=alpha;ctx.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih);ctx.restore()}
function resize(){DPR=Math.min(devicePixelRatio||1,W<700?1.3:1.55);W=innerWidth;H=innerHeight;canvas.width=Math.round(W*DPR);canvas.height=Math.round(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);buildScene();}
function buildScene(){const rng=seeded(84721);plants.length=decor.length=critters.length=motes.length=0;const bottom=H-22;
 const plantCount=clamp(Math.round(W/82),12,28);for(let i=0;i<plantCount;i++){const key=plantNames[i%plantNames.length];plants.push({key,x:(i+rng()*.7)/plantCount*W,y:bottom+rng()*8,w:42+rng()*48,phase:rng()*99,depth:rng(),tilt:(rng()-.5)*.12})}
 const decorCount=clamp(Math.round(W/165),7,15);for(let i=0;i<decorCount;i++){decor.push({key:decorNames[(i*5+2)%decorNames.length],x:(i+.25+rng()*.5)/decorCount*W,y:bottom+4,w:72+rng()*75,depth:rng(),rot:(rng()-.5)*.08})}
 for(let i=0;i<5;i++){critters.push({key:critterNames[i],x:(.08+i*.2+rng()*.07)*W,y:bottom-3-rng()*9,w:42+rng()*26,dir:rng()<.5?-1:1,speed:2+rng()*5,phase:rng()*TAU})}
 for(let i=0;i<72;i++)motes.push({x:rng()*W,y:rng()*H,r:.35+rng()*1.5,p:rng()*TAU,z:.25+rng()*.75});plants.sort((a,b)=>a.depth-b.depth);decor.sort((a,b)=>a.depth-b.depth)
}
class Fish{
 constructor(o={}){this.predator=!!o.predator;this.spec=o.spec??Math.floor(rand(0,species.length));const sp=species[this.spec];this.x=o.x??rand(80,Math.max(81,W-80));this.y=o.y??rand(90,Math.max(91,H*.69));const a=rand(0,TAU),v=this.predator?52:rand(...sp.speed);this.vx=Math.cos(a)*v;this.vy=Math.sin(a)*v*.55;this.ax=0;this.ay=0;this.size=this.predator?148:rand(...sp.size);this.baseMax=this.predator?73:sp.speed[1];this.maxForce=this.predator?46:sp.turn;this.phase=rand(0,TAU);this.wander=rand(0,100);this.protected=1.4;this.eatTimer=0;this.targetFood=null;this.target=null;this.huntClock=rand(2,5);this.dash=0;this.rest=0;}
 steer(tx,ty,max=this.baseMax,force=this.maxForce){let dx=tx-this.x,dy=ty-this.y,d=Math.hypot(dx,dy)||1;let sx=dx/d*max-this.vx,sy=dy/d*max-this.vy,m=Math.hypot(sx,sy)||1,q=Math.min(force,m)/m;return{x:sx*q,y:sy*q}}
 update(dt,now){this.ax=this.ay=0;this.protected=Math.max(0,this.protected-dt);if(this.predator)this.updatePredator(dt,now);else this.updateSchool(dt,now);const nightFactor=night?.52:1,speedFactor=cfg.speed*nightFactor*(this.eatTimer>0?.22:1);this.vx+=this.ax*dt;this.vy+=this.ay*dt;let max=this.baseMax*speedFactor*(this.predator&&this.dash>0?1.55:1),m=Math.hypot(this.vx,this.vy)||1;if(m>max){this.vx=this.vx/m*max;this.vy=this.vy/m*max}const min=this.predator?18:12;if(m<min&&this.eatTimer<=0){this.vx=this.vx/m*min;this.vy=this.vy/m*min}this.x+=this.vx*dt;this.y+=this.vy*dt;const pad=this.predator?this.size*.5:this.size*.42;this.x=clamp(this.x,pad,W-pad);this.y=clamp(this.y,65+pad*.25,H-72-pad*.18);this.eatTimer=Math.max(0,this.eatTimer-dt);this.dash=Math.max(0,this.dash-dt);}
 updateSchool(dt,now){let count=0,ax=0,ay=0,cx=0,cy=0,sx=0,sy=0;for(const o of fish){if(o===this||o.predator)continue;let dx=o.x-this.x,dy=o.y-this.y,d2=dx*dx+dy*dy;if(d2<170*170){count++;ax+=o.vx;ay+=o.vy;cx+=o.x;cy+=o.y;if(d2<58*58&&d2>0){const d=Math.sqrt(d2),q=(1-d/58)/d;sx-=dx*q;sy-=dy*q}}}if(count){ax=ax/count-this.vx;ay=ay/count-this.vy;cx=cx/count-this.x;cy=cy/count-this.y;const cm=Math.hypot(cx,cy)||1,am=Math.hypot(ax,ay)||1,sm=Math.hypot(sx,sy)||1;this.ax+=ax/am*this.maxForce*.58*cfg.alignment;this.ay+=ay/am*this.maxForce*.58*cfg.alignment;this.ax+=cx/cm*this.maxForce*.43*cfg.cohesion;this.ay+=cy/cm*this.maxForce*.43*cfg.cohesion;if(sm>0){this.ax+=sx/sm*this.maxForce*1.05*cfg.separation;this.ay+=sy/sm*this.maxForce*1.05*cfg.separation}}
 const predator=fish.find(f=>f.predator);if(predator){let dx=this.x-predator.x,dy=this.y-predator.y,d=Math.hypot(dx,dy);if(d<265&&d>0){const q=(1-d/265)*720/d;this.ax+=dx*q;this.ay+=dy*q}}
 if(scare&&now<scare.until){let dx=this.x-scare.x,dy=this.y-scare.y,d=Math.hypot(dx,dy);if(d<360&&d>0){const q=(1-d/360)*1100/d;this.ax+=dx*q;this.ay+=dy*q}}
 if(!this.targetFood||this.targetFood.dead)this.targetFood=nearestFood(this);if(this.targetFood){const d=Math.hypot(this.targetFood.x-this.x,this.targetFood.y-this.y);const q=this.steer(this.targetFood.x,this.targetFood.y,this.baseMax*1.06,this.maxForce*1.2);this.ax+=q.x*1.45;this.ay+=q.y*1.45;if(d<this.size*.23+6){this.targetFood.dead=true;this.targetFood=null;this.eatTimer=.55;playEffect('bubble',.22)}}else{this.wander+=dt*.65;this.ax+=noise1(this.wander+this.phase)*8;this.ay+=noise1(this.wander+this.phase+40)*5}
 const wall=wallForce(this,85);this.ax+=wall.x;this.ay+=wall.y;}
 updatePredator(dt){this.huntClock-=dt;this.rest=Math.max(0,this.rest-dt);if(!this.target||this.target.predator||this.huntClock<=0){this.target=selectPrey(this);this.huntClock=rand(2.2,4.6)}if(this.rest>0){this.target=null;this.ax+=noise1(elapsed*.3+this.phase)*8;this.ay+=noise1(elapsed*.3+this.phase+20)*5}else if(this.target){const d=Math.hypot(this.target.x-this.x,this.target.y-this.y),lead=clamp(d/(this.baseMax+20),.2,1.6);const tx=this.target.x+this.target.vx*lead*.78,ty=this.target.y+this.target.vy*lead*.78,q=this.steer(tx,ty,this.baseMax+(this.dash>0?42:0),this.maxForce*(this.dash>0?1.45:1));this.ax+=q.x*1.2;this.ay+=q.y*1.2;if(d<230&&this.dash<=0&&Math.random()<dt*.85)this.dash=.9;if(d<this.size*.23+this.target.size*.2&&this.target.protected<=0){respawnPrey(this.target);this.target=null;this.rest=1.7;this.huntClock=2.5}}
 const wall=wallForce(this,115);this.ax+=wall.x*1.35;this.ay+=wall.y*1.35;$('#predatorState').textContent=this.rest>0?'отдых':this.dash>0?'рывок':'охота';}
 draw(now){if(this.predator){const pitch=clamp(Math.atan2(this.vy,Math.abs(this.vx)),-.42,.42),flip=this.vx<0;ctx.save();ctx.globalAlpha=.18;ctx.fillStyle='#00101c';ctx.beginPath();ctx.ellipse(this.x,this.y+17,this.size*.47,this.size*.12,0,0,TAU);ctx.fill();ctx.restore();drawSprite('fish/barracuda',this.x,this.y,this.size,{flip,rotation:(flip?-1:1)*pitch+Math.sin(now*.009+this.phase)*.018,shadow:9});if(this.dash>0){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=this.dash*.16;ctx.strokeStyle='#9eeeff';ctx.lineWidth=3;for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(this.x-(flip?-1:1)*(this.size*.42+i*18),this.y-8+i*7);ctx.lineTo(this.x-(flip?-1:1)*(this.size*.8+i*27),this.y-8+i*7);ctx.stroke()}ctx.restore()}return}
 const sp=species[this.spec],flip=this.vx<0,pitch=clamp(Math.atan2(this.vy,Math.abs(this.vx)),-.55,.55),pulse=1+Math.sin(now*.011+this.phase)*.014;ctx.save();ctx.globalAlpha=.14;ctx.fillStyle='#00101c';ctx.beginPath();ctx.ellipse(this.x,this.y+this.size*.15,this.size*.35,this.size*.09,0,0,TAU);ctx.fill();ctx.restore();ctx.save();ctx.translate(this.x,this.y);ctx.scale(pulse,1/pulse);ctx.translate(-this.x,-this.y);drawSprite(sp.sprite,this.x,this.y,this.size,{flip,rotation:(flip?-1:1)*pitch+Math.sin(now*.008+this.phase)*.022,shadow:6});ctx.restore();if(this.eatTimer>0){ctx.fillStyle='rgba(255,242,176,.78)';ctx.beginPath();ctx.arc(this.x+(flip?-1:1)*this.size*.33,this.y+2,2.2,0,TAU);ctx.fill()}}
}
function wallForce(f,m){let x=0,y=0;if(f.x<m)x+=(m-f.x)/m*f.maxForce*1.7;if(f.x>W-m)x-=(f.x-(W-m))/m*f.maxForce*1.7;if(f.y<70+m)y+=(70+m-f.y)/m*f.maxForce*1.5;if(f.y>H-66-m)y-=(f.y-(H-66-m))/m*f.maxForce*1.8;return{x,y}}
function selectPrey(pred){let best=null,score=Infinity;for(const f of fish)if(!f.predator){const d=Math.hypot(f.x-pred.x,f.y-pred.y),edge=Math.min(f.x,W-f.x,f.y,H-f.y);const s=d+(edge<100?-40:0)+Math.hypot(f.vx,f.vy)*.2+Math.random()*35;if(s<score){score=s;best=f}}return best}
function nearestFood(f){let best=null,d2=Infinity;for(const q of food)if(!q.dead){const v=(q.x-f.x)**2+(q.y-f.y)**2;if(v<d2&&v<440*440){d2=v;best=q}}return best}
function safeSpawn(){const predator=fish.find(f=>f.predator);for(let i=0;i<25;i++){const q={x:rand(70,W-70),y:rand(90,H*.58)};if(!predator||Math.hypot(q.x-predator.x,q.y-predator.y)>330)return q}return{x:W*.12,y:H*.24}}
function respawnPrey(prey){const p=safeSpawn(),i=fish.indexOf(prey);bubbleBurst(prey.x,prey.y,18);fish[i]=new Fish({x:p.x,y:p.y,spec:prey.spec});toast('🦈 Барракуда поймала рыбку — новая уже появилась');updateCount();saveState()}
function addFish(show=true){const p=safeSpawn(),f=new Fish({x:p.x,y:p.y}),pred=fish.findIndex(x=>x.predator);pred<0?fish.push(f):fish.splice(pred,0,f);if(show)toast(`🐟 Добавлена: ${species[f.spec].name}`);updateCount();saveState()}
function feedFish(){for(let i=0;i<30;i++)food.push({x:rand(W*.14,W*.86),y:rand(-90,-8),vx:rand(-8,8),vy:rand(23,48),r:rand(2.2,4.5),phase:rand(0,TAU),dead:false});playEffect('feed',.75);toast('🍽️ Корм падает — стая меняет курс')}
function bubbleBurst(x,y,n=12){for(let i=0;i<n;i++)bubbles.push({x:x+rand(-14,14),y:y+rand(-8,8),r:rand(4,13),vy:rand(34,83),phase:rand(0,TAU),style:choice(['effects/bubble-soft','effects/bubble-outline','effects/bubble-blue']),alpha:rand(.35,.8)})}
function drawBackground(now){coverImage(assets.background,0,0,W,H,1);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,night?'rgba(0,4,15,.76)':'rgba(0,38,69,.08)');g.addColorStop(.55,night?'rgba(0,8,22,.58)':'rgba(0,43,67,.08)');g.addColorStop(1,night?'rgba(0,3,11,.78)':'rgba(0,20,29,.34)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 if(cfg.caustics){ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=night?.022:.085;ctx.beginPath();ctx.rect(0,0,W,H*.66);ctx.clip();const im=assets.caustics,size=Math.max(400,W*.46),off=(now*.012)%size;for(let y=-size;y<H*.62;y+=size*.88)for(let x=-size;x<W+size;x+=size*.9)ctx.drawImage(im,x+Math.sin(now*.00024+y)*70-off*.12,y+Math.cos(now*.00019+x)*26,size,size);ctx.restore();ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<7;i++){const x=(i+.3)/7*W+Math.sin(now*.00034+i*1.7)*70,wide=70+i*9,grad=ctx.createLinearGradient(x,0,x+wide*1.2,H);grad.addColorStop(0,night?'rgba(120,210,255,.025)':'rgba(170,244,255,.13)');grad.addColorStop(1,'rgba(130,220,255,0)');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(x-wide*.22,0);ctx.lineTo(x+wide*.22,0);ctx.lineTo(x+wide*1.3,H);ctx.lineTo(x+wide*.28,H);ctx.closePath();ctx.fill()}ctx.restore()}
 for(const m of motes){m.y-=m.z*.08;if(m.y<0)m.y=H;m.x+=Math.sin(now*.0005+m.p)*.025;ctx.fillStyle=`rgba(220,249,255,${night?.05:.09+m.z*.07})`;ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,TAU);ctx.fill()}}
function drawSeabed(now){const top=H-93;ctx.save();ctx.beginPath();ctx.moveTo(0,top);for(let x=0;x<=W+35;x+=35)ctx.lineTo(x,top+noise1(x*.025)*11);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.closePath();ctx.clip();sandPattern=sandPattern||ctx.createPattern(assets.sand,'repeat');ctx.fillStyle=sandPattern||'#b8a26f';ctx.globalAlpha=night?.32:.66;ctx.fillRect(0,top-20,W,H-top+20);const shade=ctx.createLinearGradient(0,top,0,H);shade.addColorStop(0,'rgba(30,72,70,.08)');shade.addColorStop(1,night?'rgba(0,4,9,.82)':'rgba(3,28,28,.5)');ctx.fillStyle=shade;ctx.globalAlpha=1;ctx.fillRect(0,top-20,W,H-top+20);ctx.restore()}
function drawDecor(){for(const d of decor){const scale=.72+d.depth*.44;drawSprite(d.key,d.x,d.y,d.w*scale,{rotation:d.rot,anchorY:1,alpha:night?.58:.9,shadow:8})}}
function drawPlants(now){for(const p of plants){const im=assets[p.key],sway=noise1(now*.00032+p.phase)*.11+Math.sin(now*.00055+p.phase)*.035,w=p.w*(.8+p.depth*.38),h=w*im.height/im.width;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.tilt+sway);ctx.transform(1,0,sway*.45,1,0,0);ctx.globalAlpha=night?.52:.78+p.depth*.18;ctx.drawImage(im,-w/2,-h,w,h);ctx.restore()}}
function drawCritters(dt,now){for(const c of critters){c.x+=c.dir*c.speed*dt*(night?.6:1);if(c.x<25||c.x>W-25)c.dir*=-1;const bob=Math.sin(now*.002+c.phase)*1.5;drawSprite(c.key,c.x,c.y+bob,c.w,{flip:c.dir<0,rotation:Math.sin(now*.001+c.phase)*.025,anchorY:1,alpha:night?.6:1,shadow:6})}}
function updateFood(dt,now){for(const f of food){f.vy=Math.min(59,f.vy+5*dt);f.x+=(f.vx+Math.sin(now*.003+f.phase)*9)*dt;f.y+=f.vy*dt;if(f.y>H-70)f.dead=true;ctx.save();ctx.translate(f.x,f.y);ctx.rotate(now*.0014+f.phase);ctx.fillStyle='#f7d485';ctx.shadowColor='#fff0ab';ctx.shadowBlur=5;ctx.beginPath();ctx.roundRect(-f.r,-f.r*.42,f.r*2,f.r*.84,2);ctx.fill();ctx.restore()}for(let i=food.length-1;i>=0;i--)if(food[i].dead)food.splice(i,1)}
function updateBubbles(dt,now){if(Math.random()<dt*8.5*cfg.bubbleRate)bubbles.push({x:rand(8,W-8),y:H+18,r:rand(5,16),vy:rand(24,65),phase:rand(0,TAU),style:choice(['effects/bubble-soft','effects/bubble-outline','effects/bubble-blue']),alpha:rand(.22,.62)});for(const b of bubbles){b.y-=b.vy*dt*(night?.68:1);b.x+=Math.sin(now*.0017+b.phase+b.y*.012)*12*dt;const pulse=1+Math.sin(now*.004+b.phase)*.08;drawSprite(b.style,b.x,b.y,b.r*2*pulse,{rotation:Math.sin(now*.001+b.phase)*.2,alpha:b.alpha*(night?.55:1)});if(b.y<35&&Math.random()<dt*1.8)playEffect('bubble',.035)}for(let i=bubbles.length-1;i>=0;i--)if(bubbles[i].y<-30)bubbles.splice(i,1)}
function drawVignette(){const g=ctx.createRadialGradient(W*.5,H*.42,Math.min(W,H)*.15,W*.5,H*.45,Math.max(W,H)*.72);g.addColorStop(.55,'rgba(0,8,18,0)');g.addColorStop(1,night?'rgba(0,2,9,.72)':'rgba(0,8,18,.38)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function animate(now){const dt=paused?0:Math.min((now-last)/1000,.034);last=now;if(!paused)elapsed+=dt;drawBackground(now);drawSeabed(now);drawPlants(now);drawDecor();drawCritters(dt,now);updateFood(dt,now);for(const f of fish){if(!paused)f.update(dt,now);f.draw(now)}updateBubbles(dt,now);drawVignette();if(!paused)frameCount++;if(now-fpsClock>600){$('#fps').textContent=paused?'—':Math.round(frameCount*1000/(now-fpsClock));frameCount=0;fpsClock=now}requestAnimationFrame(animate)}
function setPaused(value){paused=!!value;$('#pause').setAttribute('aria-pressed',String(paused));$('#pause').textContent=paused?'▶️ Продолжить':'⏸️ Пауза';$('#pausedLabel').classList.toggle('show',paused);last=performance.now();toast(paused?'⏸️ Симуляция поставлена на паузу':'▶️ Симуляция продолжена')}
async function toggleFullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{toast('Полноэкранный режим недоступен в этом браузере')}}
function showBootError(err){console.error(err);const loading=$('#loading');loading.classList.add('error');$('#loaderFish').textContent='⚠️';$('#loaderTitle').textContent='Аквариум не запустился';$('#loaderMessage').textContent=err&&err.message?err.message:'Неизвестная ошибка загрузки'}
async function boot(){if(booted)return;const loading=$('#loading');loading.classList.remove('done','error');$('#loaderFish').textContent='🐠';$('#loaderTitle').textContent='Заселяем аквариум';$('#loaderMessage').textContent='Подготавливаем ассеты…';try{await loadAssets();resize();syncControls();restoreState();setSound(false);booted=true;requestAnimationFrame(animate);requestAnimationFrame(()=>loading.classList.add('done'));if(location.protocol==='file:'){$('#localBadge').classList.add('show');setTimeout(()=>$('#localBadge').classList.remove('show'),4200)}}catch(err){showBootError(err)}}
function unlockAudio(){if(audioUnlocked)return;audioUnlocked=true;for(const a of Object.values(audio)){if(!a)continue;a.volume=0;const p=a.play();if(p&&p.then)p.then(()=>{a.pause();a.currentTime=0;applyVolume();if(cfg.sound)audio.ambient.play().catch(()=>{})}).catch(()=>{})}}
function applyVolume(){const v=clamp(Number(cfg.volume)||0,0,1);if(audio.ambient)audio.ambient.volume=v*.55;if(audio.feed)audio.feed.volume=v*.78;if(audio.bubble)audio.bubble.volume=v*.38}
function playEffect(key,gain=1){if(!cfg.sound||!audioUnlocked||!audio[key])return;const a=audio[key].cloneNode();a.volume=clamp(cfg.volume*gain,0,1);a.play().catch(()=>{})}
function setSound(on){cfg.sound=!!on;unlockAudio();applyVolume();if(audio.ambient){if(cfg.sound)audio.ambient.play().catch(()=>{});else audio.ambient.pause()}$('#sound').checked=cfg.sound;$('#soundBtn').setAttribute('aria-pressed',String(cfg.sound));$('#soundBtn').textContent=cfg.sound?'🔊 Звук':'🔇 Звук';saveSettings()}
function saveSettings(){writeStore('living-aquarium-settings',cfg)}
function saveState(){saveSettings();writeStore('living-aquarium-state',{night,count:fish.filter(f=>!f.predator).length,species:fish.filter(f=>!f.predator).map(f=>f.spec)})}
function restoreState(){const s=readStore('living-aquarium-state'),count=clamp(Number(s.count)||8,1,34);fish.length=0;for(let i=0;i<count;i++)fish.push(new Fish({spec:Array.isArray(s.species)?Number(s.species[i])%species.length:undefined}));fish.push(new Fish({predator:true,x:W*.74,y:H*.38}));night=!!s.night;syncNight();updateCount()}
function resetAll(){cfg={...defaults};night=false;food.length=bubbles.length=0;localStorage.removeItem('living-aquarium-settings');localStorage.removeItem('living-aquarium-state');restoreState();syncControls();setSound(false);toast('↺ Аквариум возвращён к исходным настройкам')}
function syncNight(){$('#night').setAttribute('aria-pressed',String(night));$('#night').textContent=night?'☀️ День':'🌙 Ночь'}
function updateCount(){$('#fishCount').textContent=fish.filter(f=>!f.predator).length}
function syncControls(){for(const id of['separation','alignment','cohesion','speed','bubbleRate','volume'])$('#'+id).value=cfg[id];$('#sound').checked=cfg.sound;$('#caustics').checked=cfg.caustics;for(const [id,key,d] of [['sepOut','separation',1],['aliOut','alignment',1],['cohOut','cohesion',1],['speedOut','speed',2],['bubbleOut','bubbleRate',1]])$('#'+id).textContent=Number(cfg[key]).toFixed(d);$('#volumeOut').textContent=Math.round(cfg.volume*100)+'%'}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2300)}
canvas.addEventListener('pointerdown',e=>{unlockAudio();scare={x:e.clientX,y:e.clientY,until:performance.now()+2000};bubbleBurst(e.clientX,e.clientY,14)});
$('#feed').onclick=()=>{unlockAudio();feedFish()};$('#add').onclick=()=>addFish();$('#pause').onclick=()=>setPaused(!paused);$('#fullscreen').onclick=toggleFullscreen;$('#retryLoad').onclick=()=>{booted=false;boot()};$('#night').onclick=()=>{night=!night;syncNight();saveState()};$('#settings').onclick=()=>{const open=$('#panel').classList.toggle('open');$('#settings').setAttribute('aria-pressed',String(open))};$('#soundBtn').onclick=()=>setSound(!cfg.sound);$('#sound').onchange=e=>setSound(e.target.checked);$('#caustics').onchange=e=>{cfg.caustics=e.target.checked;saveSettings()};for(const id of['separation','alignment','cohesion','speed','bubbleRate','volume'])$('#'+id).oninput=e=>{cfg[id]=Number(e.target.value);if(id==='volume')applyVolume();syncControls();saveSettings()};$('#save').onclick=()=>{saveState();toast('💾 Настройки и население сохранены')};$('#reset').onclick=resetAll;addEventListener('resize',resize,{passive:true});addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden&&audio.ambient)audio.ambient.pause();else if(cfg.sound&&audioUnlocked)audio.ambient.play().catch(()=>{})});addEventListener('keydown',e=>{if(/input|textarea|select/i.test(document.activeElement?.tagName||''))return;const k=e.key.toLowerCase();if(k===' '){e.preventDefault();setPaused(!paused)}else if(k==='f')feedFish();else if(k==='a')addFish();else if(k==='n')$('#night').click();else if(k==='m')setSound(!cfg.sound);else if(k==='s')$('#settings').click()});
boot();
})();
